name: Build and deploy

on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/hadronlang
            git pull origin master
            docker-compose up -d --build
